#!/usr/bin/env python3
import os
import os.path
import tempfile

os.chdir(os.path.dirname(os.path.realpath(__file__)))
os.chdir(os.path.join('..', 'electrum_dash'))

clonetmp = tempfile.mkdtemp()
if os.path.exists("electrum-dash-locale"):
    os.system("rm -Rf electrum-dash-locale")
if os.path.exists("locale"):
    os.system("rm -Rf locale")

# Get fresh translations
os.system("git clone https://github.com/Bertrand256/electrum-dash-locale")
os.system("mv electrum-dash-locale/locale .")

# Convert .po to .mo
print('Installing')
for lang in os.listdir('locale'):
    if lang.startswith('messages'):
        continue
    # Check LC_MESSAGES folder
    mo_dir = 'locale/%s/LC_MESSAGES' % lang
    if not os.path.exists(mo_dir):
        os.mkdir(mo_dir)
    cmd = 'msgfmt --output-file="%s/electrum.mo" "locale/%s/electrum.po"' % (mo_dir,lang)
    print('Installing', lang)
    os.system(cmd)